AWSTemplateFormatVersion: "2010-09-09"
Description: "Template for ALB RoadBalancer"

  # パラメータを設定
Parameters:
  Env:
    Type: String
    Default: AWS-Study-CFn
  ProjectName:
    Type: String
    Default: SpringBoot-sample-app-project
  TargetGroupPort:
    Type: Number
    Default: 8080
    Description: "SpringBoot APP TargetGroup Port"
  HealthCheckPort:
    Type: Number
    Default: 8080
    Description: "SpringBoot APP HealthCheck Port"

  # ターゲットグループの作成
Resources:
  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: aws-study-project-tg
      Tags:
        - Key: Name
          Value: !Ref Env
        - Key: Project
          Value: !Sub ${ProjectName}-tg
      Port: !Ref TargetGroupPort
      Protocol: HTTP
      VpcId: !ImportValue  vpc-id
      TargetType: instance
      Targets:
        - Id: !ImportValue  ec2-server-id
      HealthCheckPath: /
      HealthCheckPort: !Ref HealthCheckPort
      Matcher:
        HttpCode: 200,301
  # ロードバランサーの作成 リスナールールの設定
  ALBLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: application
      Name: ALB-Load-Balancer
      Scheme: internet-facing
      IpAddressType: ipv4
      Subnets:
        - !ImportValue public-subnet-az-1a
        - !ImportValue public-subnet-az-1c
      SecurityGroups:
        - !ImportValue alb-security-group-id
      Tags:
        - Key: Name
          Value: !Ref Env
        - Key: Project
          Value: !Sub ${ProjectName}-tg

  # リスナールール
  ALBListenerRule:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ALBTargetGroup
      LoadBalancerArn: !Ref ALBLoadBalancer
      Port: 80
      Protocol: HTTP
