AWSTemplateFormatVersion: "2010-09-09"
Description: "Template for RDS MySQL DB Server"

  # パラメータを設定
Parameters:
  InfraName:
    Type: String
    Default: AWS-Study-CFn
  ProjectName:
    Type: String
    Default: SpringBoot-sample-app
  DBInstanceClass:
    Type: String
    Default: db.m7g.large
  AllocatedStorage:
    Type: Number
    Default: 20
  MaxAllocatedStorage:
    Type: Number
    Default: 1000
  DBMasterUsername:
    Type: String
    Default: root
  DBMultiAZ:
    Type: String
    Default: true
    AllowedValues: [true, false]
  DBName:
    Type: String
    Default: awsstudy
  DeletionProtection:
    Type: String
    Default: false
    AllowedValues: [true, false]
    Description: "true is production development or leaning or staging is false"

Resources:
# 1. カスタムDBパラメーターグループの定義（ログ記録の有効化）
  RDSdbServerParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: "Custom Parameter Group for MySQL Log Export"
      Family: mysql8.4
      Parameters:
        general_log: 1
        slow_query_log: 1
        long_query_time: 2
        log_output: FILE

# SecretManagerでパスワード管理 #RDSに接続するためのパスワードをランダム作成
  RDSPasswordSecret:
    Type: AWS::SecretsManager::Secret
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Name: RDSPasswordSecret
      Description: "Create RDS password for RDS MySQL DB Server"
      GenerateSecretString:
        SecretStringTemplate: '{"username": "root"}'
        GenerateStringKey: password
        PasswordLength: 16
        ExcludeCharacters: '"@/\'
# DBサブネットグループの設定
  rdsMySQLdbServerSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "rds MySQL Subnet group"
      SubnetIds:
        - !ImportValue private-subnet-az-1a
        - !ImportValue private-subnet-az-1c
# 拡張モニタリング有効化の設定
  RDSMonitoringRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: monitoring.rds.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonRDSEnhancedMonitoringRole

# RDSの作成
  rdsMySQLdbServer:
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Type: AWS::RDS::DBInstance
    Properties:
      MultiAZ: !Ref DBMultiAZ
      Engine: mysql
      EngineVersion: 8.4.9
      DBName: !Ref DBName
      MasterUsername: !Ref DBMasterUsername
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${RDSPasswordSecret}:SecretString:password}}'
      DBInstanceClass: !Ref DBInstanceClass
      Port: 3306
      PubliclyAccessible: false
      StorageType: gp3
      AllocatedStorage: !Ref AllocatedStorage
      MaxAllocatedStorage: !Ref MaxAllocatedStorage
      VPCSecurityGroups:
        - !ImportValue rds-security-group-id
      DBSubnetGroupName: !Ref rdsMySQLdbServerSubnetGroup
      MonitoringInterval: 60
      MonitoringRoleArn: !GetAtt RDSMonitoringRole.Arn
      DBParameterGroupName: !Ref RDSdbServerParameterGroup
      EnableCloudwatchLogsExports:
        - audit
        - error
        - general
        - iam-db-auth-error
        - slowquery
      BackupRetentionPeriod: 1
      DeletionProtection: !Ref DeletionProtection
      Tags:
        - Key: Name
          Value: !Ref InfraName
        - Key: Project
          Value: !Sub ${ProjectName}-rds-server
