AWSTemplateFormatVersion: "2010-09-09"
Description: Template for EC2 RDS RoadBalancer Security-Group

Resources:

  # ec2SecurityGroup
  ec2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: EC2-Server-sg
      GroupDescription: Allow HTTP HTTPS 8080 Port
      VpcId: !ImportValue "vpc-id"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: AWS-Study-Project
        - Key: ProjectName
          Value: SpringBoot-sample-app-project

  # rdsDBSecurityGroup
  rdsDBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: rds-DB-Server-sg
      GroupDescription: Allow EC2 sg 3306 Port
      VpcId: !ImportValue "vpc-id"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref ec2SecurityGroup
      Tags:
        - Key: Name
          Value: AWS-Study-Project
        - Key: ProjectName
          Value: SpringBoot-sample-app-project

  # ALBSecurityGroup
  albSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupName: ALB-sg
      GroupDescription: Allow HTTP Port
      VpcId: !ImportValue "vpc-id"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: AWS-Study-Project
        - Key: ProjectName
          Value: SpringBoot-sample-app-project

# 外部リソースで参照するための記述
Outputs:
  CreateEC2sgId:
    Description: The ID of the created EC2 Security Group id
    Value: !Ref ec2SecurityGroup
    Export:
      Name: "ec2-security-group-id"
  CreateRDSsgId:
    Description: The ID of the created RDS Security Group id
    Value: !Ref rdsDBSecurityGroup
    Export:
      Name: "rds-security-group-id"
  CreateALBId:
    Description: The ID of the created ALB Security Group id
    Value: !Ref albSecurityGroup
    Export:
      Name: "alb-security-group-id"
